"use strict";
const path = require('path');
const express = require('express');
const body_parser_1 = require("body-parser");
const favicon = require("serve-favicon");
const health_1 = require('./routes/health');
const signup_api_1 = require('./routes/signup.api');
const rush_event_api_1 = require('./routes/rush_event.api');
const leadership_api_1 = require('./routes/leadership.api');
var app = express();
exports.app = app;
app.use(favicon(path.join(__dirname, '../public/static/favicon.png')));
app.disable("x-powered-by");
app.use(body_parser_1.json());
app.use(body_parser_1.urlencoded({ extended: true }));
app.use("/health", health_1.healthRouter);
app.use("/api/signup", signup_api_1.signupApiRouter);
app.use("/api/rushevents", rush_event_api_1.RushEventRouter);
app.use("/api/leaders", leadership_api_1.LeadershipRouter);
app.use("/", express.static(path.join(__dirname, '../public')));
//# sourceMappingURL=server.js.map