"use strict";
const path = require('path');
const express = require('express');
const body_parser_1 = require("body-parser");
const favicon = require("serve-favicon");
const health_1 = require('./routes/health');
const signupapi_1 = require('./routes/signupapi');
const authenticate_1 = require('./routes/authenticate');
const userapi_1 = require('./routes/userapi');
var app = express();
exports.app = app;
app.use(favicon(path.join(__dirname, '../public/static/favicon.png')));
app.disable("x-powered-by");
app.use(body_parser_1.json());
app.use(body_parser_1.urlencoded({ extended: true }));
app.use("/health", health_1.healthRouter);
app.use("/api/authenticate", authenticate_1.AuthRouter);
app.use("/api/signup", signupapi_1.signupApiRouter);
app.use("/api/users", userapi_1.UserApiRouter);
app.use(express.static(path.join(__dirname, '../public')));
//# sourceMappingURL=server.js.map